from __future__ import annotations

from typing import Any, Dict


PROJECT_LIST_ACTION_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "projects:create": {
        "label": "新建项目",
        "description": "打开新建项目窗口。",
        "payload_keys": ["create"],
        "payload_defaults": {"create": True},
        "input_schema": {
            "type": "object",
            "properties": {"create": {"type": "boolean", "const": True}},
            "required": ["create"],
            "additionalProperties": False,
        },
    },
    "projects:open": {
        "label": "打开项目",
        "description": "打开匹配的项目。",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "ID copied exactly from context_payload.projects[].id."},
                "projectName": {"type": "string", "description": "Human readable project name from context."},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:delete": {
        "label": "删除项目",
        "description": "删除匹配的项目。",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "destructive": True,
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "ID copied exactly from context_payload.projects[].id."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:cancel_active": {
        "label": "取消项目运行",
        "description": "取消匹配项目中的 active runtime 任务。",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "destructive": True,
        "requires_active_project": True,
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "ID copied exactly from context_payload.projects[].id."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:failed": {
        "label": "失败项目",
        "description": "筛选包含失败任务的项目。",
        "payload_keys": ["activityFilter"],
        "payload_defaults": {"activityFilter": "failed"},
        "input_schema": {
            "type": "object",
            "properties": {"activityFilter": {"type": "string", "enum": ["failed"]}},
            "required": ["activityFilter"],
            "additionalProperties": False,
        },
    },
    "projects:active": {
        "label": "运行中项目",
        "description": "筛选包含排队或运行任务的项目。",
        "payload_keys": ["activityFilter"],
        "payload_defaults": {"activityFilter": "active"},
        "input_schema": {
            "type": "object",
            "properties": {"activityFilter": {"type": "string", "enum": ["active"]}},
            "required": ["activityFilter"],
            "additionalProperties": False,
        },
    },
    "projects:clear_filters": {
        "label": "显示全部项目",
        "description": "清除项目列表筛选并恢复默认排序。",
        "payload_keys": [
            "search",
            "typeFilter",
            "stateFilter",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "sortBy",
        ],
        "payload_defaults": {
            "search": "",
            "typeFilter": "all",
            "stateFilter": "all",
            "backendFilter": "all",
            "activityFilter": "all",
            "updatedWithinDays": "all",
            "minTaskCount": "all",
            "sortBy": "updated_desc",
        },
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "enum": [""]},
                "typeFilter": {"type": "string", "enum": ["all"]},
                "stateFilter": {"type": "string", "enum": ["all"]},
                "backendFilter": {"type": "string", "enum": ["all"]},
                "activityFilter": {"type": "string", "enum": ["all"]},
                "updatedWithinDays": {"type": "string", "enum": ["all"]},
                "minTaskCount": {"type": "string", "enum": ["all"]},
                "sortBy": {"type": "string", "enum": ["updated_desc"]},
            },
            "additionalProperties": False,
        },
    },
    "projects:update_view": {
        "label": "更新项目视图",
        "description": "按用户要求组合更新项目列表搜索、筛选、排序、分页和高级筛选。",
        "payload_keys": [
            "search",
            "typeFilter",
            "stateFilter",
            "sortBy",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "pageSize",
        ],
        "requires_any_payload": [
            "search",
            "typeFilter",
            "stateFilter",
            "sortBy",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "pageSize",
        ],
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "description": "Free text for the project search box."},
                "typeFilter": {"type": "string", "enum": ["all", "prediction", "virtual_screening", "affinity", "peptide_design", "lead_optimization"]},
                "stateFilter": {"type": "string", "enum": ["all", "DRAFT", "QUEUED", "RUNNING", "SUCCESS", "FAILURE", "REVOKED"]},
                "sortBy": {"type": "string", "enum": ["updated_desc", "updated_asc", "created_desc", "created_asc", "name_asc", "name_desc"]},
                "backendFilter": {"type": "string", "description": "Backend token from context projects, or all."},
                "activityFilter": {"type": "string", "enum": ["all", "active", "completed", "failed", "no_tasks"]},
                "updatedWithinDays": {"type": "string", "enum": ["all", "1", "7", "30", "90"]},
                "minTaskCount": {"type": "string", "enum": ["all", "1", "3", "5", "10"]},
                "pageSize": {"type": "integer", "enum": [8, 12, 20, 50]},
            },
            "additionalProperties": False,
        },
    },
    "projects:workflow_prediction": {
        "label": "Prediction 项目",
        "description": "筛选结构预测 workflow 项目。",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "prediction"},
    },
    "projects:workflow_virtual_screening": {
        "label": "Virtual Screening 项目",
        "description": "筛选 Nesso-1 Virtual Screening workflow 项目。",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "virtual_screening"},
    },
    "projects:workflow_affinity": {
        "label": "Affinity 项目",
        "description": "筛选 Affinity Scoring workflow 项目。",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "affinity"},
    },
    "projects:workflow_peptide_design": {
        "label": "Peptide Design 项目",
        "description": "筛选 Peptide Design workflow 项目。",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "peptide_design"},
    },
    "projects:workflow_lead_optimization": {
        "label": "Lead Optimization 项目",
        "description": "筛选 Lead Optimization workflow 项目。",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "lead_optimization"},
    },
    "projects:updated_desc": {
        "label": "最新更新",
        "description": "按最近更新时间降序排序。",
        "payload_keys": ["sortBy"],
        "payload_defaults": {"sortBy": "updated_desc"},
    },
    "projects:updated_asc": {
        "label": "最早更新",
        "description": "按最近更新时间升序排序。",
        "payload_keys": ["sortBy"],
        "payload_defaults": {"sortBy": "updated_asc"},
    },
    "projects:backend_boltz": {
        "label": "Boltz 项目",
        "description": "筛选 Boltz backend 项目。",
        "payload_keys": ["backendFilter"],
        "payload_defaults": {"backendFilter": "boltz"},
    },
}
