from __future__ import annotations

from typing import Any, Dict


PROJECT_LIST_ACTION_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "projects:create": {
        "label": "New project",
        "description": "Open the new-project dialog.",
        "payload_keys": ["create"],
        "payload_defaults": {"create": True},
        "input_schema": {
            "type": "object",
            "properties": {"create": {"type": "boolean", "const": True}},
            "required": ["create"],
            "additionalProperties": False,
        },
    },
    "projects:open": {
        "label": "Open project",
        "description": "Open the matching project.",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "ID copied exactly from context_payload.projects[].id."},
                "projectName": {"type": "string", "description": "Human readable project name from context."},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:delete": {
        "label": "Delete project",
        "description": "Delete the matching project.",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "destructive": True,
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "ID copied exactly from context_payload.projects[].id."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:cancel_active": {
        "label": "Cancel project runs",
        "description": "Cancel the active runtime tasks in the matching project.",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "destructive": True,
        "requires_active_project": True,
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "ID copied exactly from context_payload.projects[].id."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:failed": {
        "label": "Failed projects",
        "description": "Filter for projects that contain failed tasks.",
        "payload_keys": ["activityFilter"],
        "payload_defaults": {"activityFilter": "failed"},
        "input_schema": {
            "type": "object",
            "properties": {"activityFilter": {"type": "string", "enum": ["failed"]}},
            "required": ["activityFilter"],
            "additionalProperties": False,
        },
    },
    "projects:active": {
        "label": "Active projects",
        "description": "Filter for projects with queued or running tasks.",
        "payload_keys": ["activityFilter"],
        "payload_defaults": {"activityFilter": "active"},
        "input_schema": {
            "type": "object",
            "properties": {"activityFilter": {"type": "string", "enum": ["active"]}},
            "required": ["activityFilter"],
            "additionalProperties": False,
        },
    },
    "projects:clear_filters": {
        "label": "Show all projects",
        "description": "Clear project-list filters and restore the default sorting.",
        "payload_keys": [
            "search",
            "typeFilter",
            "stateFilter",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "sortBy",
        ],
        "payload_defaults": {
            "search": "",
            "typeFilter": "all",
            "stateFilter": "all",
            "backendFilter": "all",
            "activityFilter": "all",
            "updatedWithinDays": "all",
            "minTaskCount": "all",
            "sortBy": "updated_desc",
        },
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "enum": [""]},
                "typeFilter": {"type": "string", "enum": ["all"]},
                "stateFilter": {"type": "string", "enum": ["all"]},
                "backendFilter": {"type": "string", "enum": ["all"]},
                "activityFilter": {"type": "string", "enum": ["all"]},
                "updatedWithinDays": {"type": "string", "enum": ["all"]},
                "minTaskCount": {"type": "string", "enum": ["all"]},
                "sortBy": {"type": "string", "enum": ["updated_desc"]},
            },
            "additionalProperties": False,
        },
    },
    "projects:update_view": {
        "label": "Update project view",
        "description": "Combine and update the project-list search, filters, sorting, paging, and advanced filters as requested by the user.",
        "payload_keys": [
            "search",
            "typeFilter",
            "stateFilter",
            "sortBy",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "pageSize",
        ],
        "requires_any_payload": [
            "search",
            "typeFilter",
            "stateFilter",
            "sortBy",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "pageSize",
        ],
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "description": "Free text for the project search box."},
                "typeFilter": {"type": "string", "enum": ["all", "prediction", "virtual_screening", "affinity", "peptide_design", "lead_optimization"]},
                "stateFilter": {"type": "string", "enum": ["all", "DRAFT", "QUEUED", "RUNNING", "SUCCESS", "FAILURE", "REVOKED"]},
                "sortBy": {"type": "string", "enum": ["updated_desc", "updated_asc", "created_desc", "created_asc", "name_asc", "name_desc"]},
                "backendFilter": {"type": "string", "description": "Backend token from context projects, or all."},
                "activityFilter": {"type": "string", "enum": ["all", "active", "completed", "failed", "no_tasks"]},
                "updatedWithinDays": {"type": "string", "enum": ["all", "1", "7", "30", "90"]},
                "minTaskCount": {"type": "string", "enum": ["all", "1", "3", "5", "10"]},
                "pageSize": {"type": "integer", "enum": [8, 12, 20, 50]},
            },
            "additionalProperties": False,
        },
    },
    "projects:workflow_prediction": {
        "label": "Prediction projects",
        "description": "Filter for structure-prediction workflow projects.",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "prediction"},
    },
    "projects:workflow_virtual_screening": {
        "label": "Virtual Screening projects",
        "description": "Filter for Nesso-1 Virtual Screening workflow projects.",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "virtual_screening"},
    },
    "projects:workflow_affinity": {
        "label": "Affinity projects",
        "description": "Filter for Affinity Scoring workflow projects.",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "affinity"},
    },
    "projects:workflow_peptide_design": {
        "label": "Peptide Design projects",
        "description": "Filter for Peptide Design workflow projects.",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "peptide_design"},
    },
    "projects:workflow_lead_optimization": {
        "label": "Lead Optimization projects",
        "description": "Filter for Lead Optimization workflow projects.",
        "payload_keys": ["workflowFilter"],
        "payload_defaults": {"workflowFilter": "lead_optimization"},
    },
    "projects:updated_desc": {
        "label": "Newest updated",
        "description": "Sort by most-recently-updated, descending.",
        "payload_keys": ["sortBy"],
        "payload_defaults": {"sortBy": "updated_desc"},
    },
    "projects:updated_asc": {
        "label": "Oldest updated",
        "description": "Sort by most-recently-updated, ascending.",
        "payload_keys": ["sortBy"],
        "payload_defaults": {"sortBy": "updated_asc"},
    },
    "projects:backend_boltz": {
        "label": "Boltz projects",
        "description": "Filter for Boltz-backend projects.",
        "payload_keys": ["backendFilter"],
        "payload_defaults": {"backendFilter": "boltz"},
    },
}
