from __future__ import annotations

from typing import Any, Dict


PROJECT_LIST_ACTION_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "projects:create": {
        "label": "New project",
        "description": "Create a new project. Pass the workflow type the user requested.",
        "target_context": "task_list",
        "payload_keys": ["create", "workflow"],
        "payload_defaults": {"create": True},
        "input_schema": {
            "type": "object",
            "properties": {
                "create": {"type": "boolean", "const": True},
                "workflow": {"type": "string", "enum": ["prediction", "virtual_screening", "affinity", "peptide_design", "lead_optimization"], "description": "The project's workflow type."},
            },
            "required": ["create"],
            "additionalProperties": False,
        },
    },
    "projects:open": {
        "label": "Open project",
        "description": "Navigate into a project's task list. Requires the project ID from the visible project list.",
        "target_context": "task_list",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "Project ID from the visible list."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:rename": {
        "label": "Rename project",
        "description": "Change a project's name. Requires the project ID and the new name.",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId", "projectName"],
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "Project ID from the visible list."},
                "projectName": {"type": "string", "minLength": 1, "description": "The new project name."},
            },
            "required": ["projectId", "projectName"],
            "additionalProperties": False,
        },
    },
    "projects:delete": {
        "label": "Delete project",
        "description": "Permanently delete a project and all its tasks. Requires the project ID.",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "destructive": True,
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "Project ID from the visible list."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:cancel_active": {
        "label": "Cancel project runs",
        "description": "Stop all queued and running tasks in a project. Requires the project ID.",
        "payload_keys": ["projectId", "projectName"],
        "requires_payload": ["projectId"],
        "destructive": True,
        "input_schema": {
            "type": "object",
            "properties": {
                "projectId": {"type": "string", "description": "Project ID from the visible list."},
                "projectName": {"type": "string"},
            },
            "required": ["projectId"],
            "additionalProperties": False,
        },
    },
    "projects:failed": {
        "label": "Failed projects",
        "description": "Filter for projects that contain failed tasks.",
        "payload_keys": ["activityFilter"],
        "payload_defaults": {"activityFilter": "failed"},
        "input_schema": {
            "type": "object",
            "properties": {"activityFilter": {"type": "string", "enum": ["failed"]}},
            "required": ["activityFilter"],
            "additionalProperties": False,
        },
    },
    "projects:active": {
        "label": "Active projects",
        "description": "Filter for projects with queued or running tasks.",
        "payload_keys": ["activityFilter"],
        "payload_defaults": {"activityFilter": "active"},
        "input_schema": {
            "type": "object",
            "properties": {"activityFilter": {"type": "string", "enum": ["active"]}},
            "required": ["activityFilter"],
            "additionalProperties": False,
        },
    },
    "projects:clear_filters": {
        "label": "Show all projects",
        "description": "Clear project-list filters and restore the default sorting.",
        "payload_keys": [
            "search",
            "typeFilter",
            "stateFilter",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "sortBy",
        ],
        "payload_defaults": {
            "search": "",
            "typeFilter": "all",
            "stateFilter": "all",
            "backendFilter": "all",
            "activityFilter": "all",
            "updatedWithinDays": "all",
            "minTaskCount": "all",
            "sortBy": "updated_desc",
        },
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "enum": [""]},
                "typeFilter": {"type": "string", "enum": ["all"]},
                "stateFilter": {"type": "string", "enum": ["all"]},
                "backendFilter": {"type": "string", "enum": ["all"]},
                "activityFilter": {"type": "string", "enum": ["all"]},
                "updatedWithinDays": {"type": "string", "enum": ["all"]},
                "minTaskCount": {"type": "string", "enum": ["all"]},
                "sortBy": {"type": "string", "enum": ["updated_desc"]},
            },
            "additionalProperties": False,
        },
    },
    "projects:update_view": {
        "label": "Filter or sort projects",
        "description": "Filter and sort the project list: search by text, filter by workflow type / state / activity / backend, sort by date or name, change page size. Pass only the fields the user wants to change.",
        "payload_keys": [
            "search",
            "typeFilter",
            "stateFilter",
            "sortBy",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "pageSize",
        ],
        "requires_any_payload": [
            "search",
            "typeFilter",
            "stateFilter",
            "sortBy",
            "backendFilter",
            "activityFilter",
            "updatedWithinDays",
            "minTaskCount",
            "pageSize",
        ],
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "description": "Free text search."},
                "typeFilter": {"type": "string", "enum": ["all", "prediction", "virtual_screening", "affinity", "peptide_design", "lead_optimization"]},
                "stateFilter": {"type": "string", "enum": ["all", "DRAFT", "QUEUED", "RUNNING", "SUCCESS", "FAILURE", "REVOKED"]},
                "sortBy": {"type": "string", "enum": ["updated_desc", "updated_asc", "created_desc", "created_asc", "name_asc", "name_desc"]},
                "backendFilter": {"type": "string", "description": "Backend name or 'all'."},
                "activityFilter": {"type": "string", "enum": ["all", "active", "completed", "failed", "no_tasks"]},
                "updatedWithinDays": {"type": "string", "enum": ["all", "1", "7", "30", "90"]},
                "minTaskCount": {"type": "string", "enum": ["all", "1", "3", "5", "10"]},
                "pageSize": {"type": "integer", "enum": [8, 12, 20, 50]},
            },
            "additionalProperties": False,
        },
    },
}
