from __future__ import annotations

from typing import Any, Dict


TASK_LIST_ACTION_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "tasks:open": {
        "label": "打开任务",
        "description": "打开匹配的任务。",
        "payload_keys": ["taskRowId", "taskName"],
        "requires_payload": ["taskRowId"],
        "input_schema": {
            "type": "object",
            "properties": {
                "taskRowId": {"type": "string", "description": "ID copied exactly from context_payload.rows[].id."},
                "taskName": {"type": "string"},
            },
            "required": ["taskRowId"],
            "additionalProperties": False,
        },
    },
    "tasks:create": {
        "label": "新建任务",
        "description": "在当前项目中新建任务。",
        "payload_keys": ["create"],
        "payload_defaults": {"create": True},
    },
    "tasks:create_with_sequence": {
        "label": "新建预测任务",
        "description": "创建包含结构化组件列表的新预测任务。",
        "payload_keys": ["create", "components"],
        "requires_workflow": ["prediction"],
        "requires_payload": ["components"],
        "payload_defaults": {"create": True},
        "input_schema": {
            "type": "object",
            "properties": {
                "create": {"type": "boolean", "const": True},
                "components": {
                    "type": "array",
                    "description": "Every structural component copied from the user request. Required for both protein-only and multi-component tasks.",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": ["protein", "ligand", "dna", "rna"],
                                "description": "Use ligand for small molecules, compounds, CCD IDs, and SMILES strings.",
                            },
                            "sequence": {
                                "type": "string",
                                "description": "Protein/DNA/RNA sequence, ligand SMILES, or ligand CCD ID.",
                            },
                            "numCopies": {"type": "integer", "minimum": 1},
                            "useMsa": {"type": "boolean"},
                            "inputMethod": {"type": "string", "enum": ["smiles", "ccd"]},
                        },
                        "required": ["type", "sequence"],
                        "additionalProperties": False,
                    },
                },
            },
            "required": ["create", "components"],
            "additionalProperties": False,
        },
    },
    "tasks:copy_with_patch": {
        "label": "复制任务并修改参数",
        "description": "从任务列表中选择一个已有任务，复制为新 draft，应用结构化参数/组件 patch，并在任务详情页继续确认运行。",
        "payload_keys": ["taskRowId", "taskName", "parameterPatch"],
        "requires_workflow": ["prediction"],
        "requires_payload": ["taskRowId", "parameterPatch"],
        "input_schema": {
            "type": "object",
            "properties": {
                "taskRowId": {
                    "type": "string",
                    "description": "ID copied exactly from context_payload.rows[].id for the task selected by the user's criterion, e.g. highest ipTM.",
                },
                "taskName": {"type": "string"},
                "parameterPatch": {
                    "type": "object",
                    "description": "Patch to apply after copying the source task. Include only requested changes.",
                    "properties": {
                        "backend": {
                            "type": "string",
                            "enum": ["boltz", "alphafold3", "protenix"],
                            "description": "Requested structure-prediction backend. Map AlphaFold/AF3 to alphafold3.",
                        },
                        "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
                        "componentsAdd": {
                            "type": "array",
                            "description": "Legacy shortcut for componentsPatch append operations. Prefer componentsPatch for new plans.",
                            "items": {"type": "object"},
                        },
                        "componentsReplacement": {
                            "type": "object",
                            "description": "Legacy shortcut for componentsPatch replace_all operations. Prefer componentsPatch for new plans.",
                            "properties": {"mode": {"type": "string"}, "components": {"type": "array", "items": {"type": "object"}}, "clearConstraints": {"type": "boolean"}},
                        },
                        "componentsPatch": {
                            "type": "array",
                            "description": "Ordered component operations to apply to the copied source task.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "op": {"type": "string", "enum": ["append", "update", "remove", "replace_all"]},
                                    "selector": {
                                        "type": "object",
                                        "description": "Existing component selector for update/remove: id, 1-based index, type, or sequenceContains.",
                                    },
                                    "component": {
                                        "type": "object",
                                        "description": "Full component for append or partial fields for update: type, sequence, numCopies, useMsa, inputMethod.",
                                    },
                                    "components": {
                                        "type": "array",
                                        "description": "Full final component list for replace_all.",
                                        "items": {"type": "object"},
                                    },
                                },
                                "required": ["op"],
                                "additionalProperties": False,
                            },
                        },
                    },
                    "additionalProperties": False,
                },
            },
            "required": ["taskRowId", "parameterPatch"],
            "additionalProperties": False,
        },
    },
    "tasks:delete": {
        "label": "删除任务",
        "description": "删除匹配的任务记录。",
        "payload_keys": ["taskRowId", "taskName"],
        "requires_payload": ["taskRowId"],
        "destructive": True,
    },
    "tasks:rename": {
        "label": "重命名任务",
        "description": "更新匹配任务的名称或描述。",
        "payload_keys": ["taskRowId", "taskName", "taskSummary"],
        "requires_payload": ["taskRowId"],
    },
    "tasks:cancel": {
        "label": "取消任务",
        "description": "取消或终止匹配的运行/排队任务。",
        "payload_keys": ["taskRowId", "taskName"],
        "requires_payload": ["taskRowId"],
        "destructive": True,
        "requires_active_task": True,
    },
    "tasks:failure": {"label": "失败任务", "description": "筛选 FAILURE 任务。", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "FAILURE"}},
    "tasks:running": {"label": "运行任务", "description": "筛选 RUNNING 任务。", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "RUNNING"}},
    "tasks:queued": {"label": "排队任务", "description": "筛选 QUEUED 任务。", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "QUEUED"}},
    "tasks:success": {"label": "成功任务", "description": "筛选 SUCCESS 任务。", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "SUCCESS"}},
    "tasks:clear_filters": {
        "label": "显示全部任务",
        "description": "清除任务列表筛选并恢复默认排序。",
        "payload_keys": ["stateFilter", "workflowFilter", "backendFilter", "sortKey", "clearAdvancedFilters", "clearSearch"],
        "payload_defaults": {
            "stateFilter": "all",
            "workflowFilter": "all",
            "backendFilter": "all",
            "sortKey": "submitted",
            "clearAdvancedFilters": True,
            "clearSearch": True,
        },
        "input_schema": {
            "type": "object",
            "properties": {
                "stateFilter": {"type": "string", "enum": ["all"]},
                "workflowFilter": {"type": "string", "enum": ["all"]},
                "backendFilter": {"type": "string", "enum": ["all"]},
                "sortKey": {"type": "string", "enum": ["submitted"]},
                "clearAdvancedFilters": {"type": "boolean", "const": True},
                "clearSearch": {"type": "boolean", "const": True},
            },
            "additionalProperties": False,
        },
    },
    "tasks:update_view": {
        "label": "更新任务视图",
        "description": "按用户要求组合更新任务列表搜索、筛选、排序、分页和高级筛选。",
        "payload_keys": [
            "search",
            "stateFilter",
            "workflowFilter",
            "backendFilter",
            "sortKey",
            "sortDirection",
            "pageSize",
            "submittedWithinDays",
            "seedFilter",
            "failureOnly",
            "minPlddt",
            "minIptm",
            "maxPae",
            "visibleMetricColumns",
        ],
        "requires_any_payload": [
            "search",
            "stateFilter",
            "workflowFilter",
            "backendFilter",
            "sortKey",
            "sortDirection",
            "pageSize",
            "submittedWithinDays",
            "seedFilter",
            "failureOnly",
            "minPlddt",
            "minIptm",
            "maxPae",
            "visibleMetricColumns",
        ],
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "description": "Free text for the task search box."},
                "stateFilter": {"type": "string", "enum": ["all", "DRAFT", "QUEUED", "RUNNING", "SUCCESS", "FAILURE", "REVOKED"]},
                "workflowFilter": {"type": "string", "enum": ["all", "prediction", "virtual_screening", "affinity", "peptide_design", "lead_optimization"]},
                "backendFilter": {"type": "string", "description": "Backend token from context rows, or all."},
                "sortKey": {"type": "string", "enum": ["submitted", "plddt", "ipsae", "iptm", "pae", "backend", "seed", "mode"]},
                "sortDirection": {"type": "string", "enum": ["asc", "desc"]},
                "pageSize": {"type": "integer", "enum": [8, 12, 20, 50]},
                "submittedWithinDays": {"type": "string", "enum": ["all", "1", "7", "30", "90"]},
                "seedFilter": {"type": "string", "enum": ["all", "with_seed", "without_seed"]},
                "failureOnly": {"type": "boolean"},
                "minPlddt": {"type": "number", "minimum": 0, "maximum": 100},
                "minIptm": {"type": "number", "minimum": 0, "maximum": 1},
                "maxPae": {"type": "number", "minimum": 0},
                "visibleMetricColumns": {
                    "type": "array",
                    "items": {"type": "string", "enum": ["plddt", "ipsae", "iptm", "pae"]},
                    "minItems": 1,
                    "uniqueItems": True,
                },
            },
            "additionalProperties": False,
        },
    },
    "tasks:submitted": {"label": "提交时间", "description": "按提交时间排序。", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "submitted"}},
    "tasks:sort_plddt": {"label": "按 pLDDT 排序", "description": "按 pLDDT 从高到低排序。", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "plddt"}},
    "tasks:sort_iptm": {"label": "按 ipTM 排序", "description": "按 ipTM 从高到低排序。", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "iptm"}},
    "tasks:sort_ipsae": {"label": "按 IPSAE 排序", "description": "按 IPSAE 从高到低排序。", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "ipsae"}},
    "tasks:sort_pae": {"label": "按 PAE 排序", "description": "按 PAE 从低到高排序。", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "pae"}},
    "tasks:backend_boltz": {"label": "Boltz 任务", "description": "筛选 Boltz backend 任务。", "payload_keys": ["backendFilter"], "payload_defaults": {"backendFilter": "boltz"}},
}
