from __future__ import annotations

from typing import Any, Dict


TASK_LIST_ACTION_SCHEMAS: Dict[str, Dict[str, Any]] = {
    "tasks:open": {
        "label": "Open task",
        "description": "Open the matching task.",
        "payload_keys": ["taskRowId", "taskName"],
        "requires_payload": ["taskRowId"],
        "input_schema": {
            "type": "object",
            "properties": {
                "taskRowId": {"type": "string", "description": "ID copied exactly from context_payload.rows[].id."},
                "taskName": {"type": "string"},
            },
            "required": ["taskRowId"],
            "additionalProperties": False,
        },
    },
    "tasks:create": {
        "label": "New task",
        "description": "Create a new task in the current project.",
        "payload_keys": ["create"],
        "payload_defaults": {"create": True},
    },
    "tasks:create_with_sequence": {
        "label": "New task (with components)",
        "description": "Create a new task prefilled with a structured component list (protein / small molecule / DNA / RNA). Applies to structure-prediction and peptide-design tasks.",
        "payload_keys": ["create", "components"],
        "requires_workflow": ["prediction", "peptide_design"],
        "requires_payload": ["components"],
        "payload_defaults": {"create": True},
        "input_schema": {
            "type": "object",
            "properties": {
                "create": {"type": "boolean", "const": True},
                "components": {
                    "type": "array",
                    "description": "Every structural component copied from the user request. Required for both protein-only and multi-component tasks.",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": ["protein", "ligand", "dna", "rna"],
                                "description": "Use ligand for small molecules, compounds, CCD IDs, and SMILES strings.",
                            },
                            "sequence": {
                                "type": "string",
                                "description": "Protein/DNA/RNA sequence, ligand SMILES, or ligand CCD ID.",
                            },
                            "numCopies": {"type": "integer", "minimum": 1},
                            "useMsa": {"type": "boolean"},
                            "inputMethod": {"type": "string", "enum": ["smiles", "ccd"]},
                        },
                        "required": ["type", "sequence"],
                        "additionalProperties": False,
                    },
                },
            },
            "required": ["create", "components"],
            "additionalProperties": False,
        },
    },
    "tasks:create_virtual_screening": {
        "label": "New virtual-screening task",
        "description": "Create a virtual-screening task: one or more protein target components plus a library of small-molecule compounds (by SMILES) to screen against the target.",
        "payload_keys": ["create", "components", "screeningCompounds"],
        "requires_workflow": ["virtual_screening"],
        "requires_payload": ["components", "screeningCompounds"],
        "payload_defaults": {"create": True},
        "input_schema": {
            "type": "object",
            "properties": {
                "create": {"type": "boolean", "const": True},
                "components": {
                    "type": "array",
                    "description": "Target structural component(s): at least one protein. Fixed context ligands may be added here; the screened compound library goes in screeningCompounds.",
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "string",
                                "enum": ["protein", "ligand", "dna", "rna"],
                                "description": "Use ligand for a fixed context molecule (not the screened library).",
                            },
                            "sequence": {"type": "string", "description": "Protein/DNA/RNA sequence or ligand SMILES/CCD ID."},
                            "numCopies": {"type": "integer", "minimum": 1},
                            "useMsa": {"type": "boolean"},
                            "inputMethod": {"type": "string", "enum": ["smiles", "ccd"]},
                        },
                        "required": ["type", "sequence"],
                        "additionalProperties": False,
                    },
                },
                "screeningCompounds": {
                    "type": "array",
                    "description": "The compound library to screen: each entry is one small molecule by SMILES (optional name). Use one entry per compound; 1 to 200 entries.",
                    "minItems": 1,
                    "maxItems": 200,
                    "items": {
                        "type": "object",
                        "properties": {
                            "smiles": {"type": "string", "minLength": 1},
                            "name": {"type": "string"},
                        },
                        "required": ["smiles"],
                        "additionalProperties": False,
                    },
                },
            },
            "required": ["create", "components", "screeningCompounds"],
            "additionalProperties": False,
        },
    },
    "tasks:copy_with_patch": {
        "label": "Copy task and edit parameters",
        "description": "Select an existing task from the task list, copy it into a new draft, apply a structured parameter/component patch, and continue confirming the run on the task-detail page.",
        "payload_keys": ["taskRowId", "taskName", "parameterPatch"],
        "requires_workflow": ["prediction"],
        "requires_payload": ["taskRowId", "parameterPatch"],
        "input_schema": {
            "type": "object",
            "properties": {
                "taskRowId": {
                    "type": "string",
                    "description": "ID copied exactly from the selected task row in the provided context.",
                },
                "taskName": {"type": "string"},
                "parameterPatch": {
                    "type": "object",
                    "description": "Patch to apply after copying the source task. Include only requested changes.",
                    "properties": {
                        "backend": {
                            "type": "string",
                            "enum": ["boltz", "alphafold3", "protenix"],
                            "description": "Requested structure-prediction backend. Map AlphaFold/AF3 to alphafold3.",
                        },
                        "seed": {"type": "integer", "minimum": 0, "maximum": 2147483647},
                        "componentsAdd": {
                            "type": "array",
                            "description": "Legacy shortcut for componentsPatch append operations. Prefer componentsPatch for new plans.",
                            "items": {"type": "object"},
                        },
                        "componentsReplacement": {
                            "type": "object",
                            "description": "Legacy shortcut for componentsPatch replace_all operations. Prefer componentsPatch for new plans.",
                            "properties": {"mode": {"type": "string"}, "components": {"type": "array", "items": {"type": "object"}}, "clearConstraints": {"type": "boolean"}},
                        },
                        "componentsPatch": {
                            "type": "array",
                            "description": "Ordered component operations to apply to the copied source task.",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "op": {"type": "string", "enum": ["append", "update", "remove", "replace_all"]},
                                    "selector": {
                                        "type": "object",
                                        "description": "Existing component selector for update/remove: id, 1-based index, type, or sequenceContains.",
                                    },
                                    "component": {
                                        "type": "object",
                                        "description": "Full component for append or partial fields for update: type, sequence, numCopies, useMsa, inputMethod.",
                                    },
                                    "components": {
                                        "type": "array",
                                        "description": "Full final component list for replace_all.",
                                        "items": {"type": "object"},
                                    },
                                },
                                "required": ["op"],
                                "additionalProperties": False,
                            },
                        },
                    },
                    "additionalProperties": False,
                },
            },
            "required": ["taskRowId", "parameterPatch"],
            "additionalProperties": False,
        },
    },
    "tasks:delete": {
        "label": "Delete task",
        "description": "Delete the matching task record.",
        "payload_keys": ["taskRowId", "taskName"],
        "requires_payload": ["taskRowId"],
        "destructive": True,
    },
    "tasks:rename": {
        "label": "Rename task",
        "description": "Update the name or description of the matching task.",
        "payload_keys": ["taskRowId", "taskName", "taskSummary"],
        "requires_payload": ["taskRowId"],
    },
    "tasks:cancel": {
        "label": "Cancel task",
        "description": "Cancel or terminate the matching running or queued task.",
        "payload_keys": ["taskRowId", "taskName"],
        "requires_payload": ["taskRowId"],
        "destructive": True,
        "requires_active_task": True,
    },
    "tasks:failure": {"label": "Failed tasks", "description": "Filter for FAILURE tasks.", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "FAILURE"}},
    "tasks:running": {"label": "Running tasks", "description": "Filter for RUNNING tasks.", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "RUNNING"}},
    "tasks:queued": {"label": "Queued tasks", "description": "Filter for QUEUED tasks.", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "QUEUED"}},
    "tasks:success": {"label": "Succeeded tasks", "description": "Filter for SUCCESS tasks.", "payload_keys": ["stateFilter"], "payload_defaults": {"stateFilter": "SUCCESS"}},
    "tasks:clear_filters": {
        "label": "Show all tasks",
        "description": "Clear task-list filters and restore the default sorting.",
        "payload_keys": ["stateFilter", "workflowFilter", "backendFilter", "sortKey", "clearAdvancedFilters", "clearSearch"],
        "payload_defaults": {
            "stateFilter": "all",
            "workflowFilter": "all",
            "backendFilter": "all",
            "sortKey": "submitted",
            "clearAdvancedFilters": True,
            "clearSearch": True,
        },
        "input_schema": {
            "type": "object",
            "properties": {
                "stateFilter": {"type": "string", "enum": ["all"]},
                "workflowFilter": {"type": "string", "enum": ["all"]},
                "backendFilter": {"type": "string", "enum": ["all"]},
                "sortKey": {"type": "string", "enum": ["submitted"]},
                "clearAdvancedFilters": {"type": "boolean", "const": True},
                "clearSearch": {"type": "boolean", "const": True},
            },
            "additionalProperties": False,
        },
    },
    "tasks:update_view": {
        "label": "Update task view",
        "description": "Combine and update the task-list search, filters, sorting, paging, and advanced filters as requested by the user.",
        "payload_keys": [
            "search",
            "stateFilter",
            "workflowFilter",
            "backendFilter",
            "sortKey",
            "sortDirection",
            "pageSize",
            "submittedWithinDays",
            "seedFilter",
            "failureOnly",
            "minPlddt",
            "minIptm",
            "maxPae",
            "visibleMetricColumns",
        ],
        "requires_any_payload": [
            "search",
            "stateFilter",
            "workflowFilter",
            "backendFilter",
            "sortKey",
            "sortDirection",
            "pageSize",
            "submittedWithinDays",
            "seedFilter",
            "failureOnly",
            "minPlddt",
            "minIptm",
            "maxPae",
            "visibleMetricColumns",
        ],
        "input_schema": {
            "type": "object",
            "properties": {
                "search": {"type": "string", "description": "Free text for the task search box."},
                "stateFilter": {"type": "string", "enum": ["all", "DRAFT", "QUEUED", "RUNNING", "SUCCESS", "FAILURE", "REVOKED"]},
                "workflowFilter": {"type": "string", "enum": ["all", "prediction", "virtual_screening", "affinity", "peptide_design", "lead_optimization"]},
                "backendFilter": {"type": "string", "description": "Backend token from context rows, or all."},
                "sortKey": {"type": "string", "enum": ["submitted", "plddt", "ipsae", "iptm", "pae", "backend", "seed", "mode"]},
                "sortDirection": {"type": "string", "enum": ["asc", "desc"]},
                "pageSize": {"type": "integer", "enum": [8, 12, 20, 50]},
                "submittedWithinDays": {"type": "string", "enum": ["all", "1", "7", "30", "90"]},
                "seedFilter": {"type": "string", "enum": ["all", "with_seed", "without_seed"]},
                "failureOnly": {"type": "boolean"},
                "minPlddt": {"type": "number", "minimum": 0, "maximum": 100},
                "minIptm": {"type": "number", "minimum": 0, "maximum": 1},
                "maxPae": {"type": "number", "minimum": 0},
                "visibleMetricColumns": {
                    "type": "array",
                    "items": {"type": "string", "enum": ["plddt", "ipsae", "iptm", "pae"]},
                    "minItems": 1,
                    "uniqueItems": True,
                },
            },
            "additionalProperties": False,
        },
    },
    "tasks:submitted": {"label": "Submitted time", "description": "Sort by submitted time.", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "submitted"}},
    "tasks:sort_plddt": {"label": "Sort by pLDDT", "description": "Sort by pLDDT, high to low.", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "plddt"}},
    "tasks:sort_iptm": {"label": "Sort by ipTM", "description": "Sort by ipTM, high to low.", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "iptm"}},
    "tasks:sort_ipsae": {"label": "Sort by IPSAE", "description": "Sort by IPSAE, high to low.", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "ipsae"}},
    "tasks:sort_pae": {"label": "Sort by PAE", "description": "Sort by PAE, low to high.", "payload_keys": ["sortKey"], "payload_defaults": {"sortKey": "pae"}},
    "tasks:backend_boltz": {"label": "Boltz tasks", "description": "Filter for Boltz-backend tasks.", "payload_keys": ["backendFilter"], "payload_defaults": {"backendFilter": "boltz"}},
}
