import { describe, expect, it } from 'vitest';
import { parseVirtualScreeningInput } from './virtualScreening';

// Full parity battery: expected values generated by the runtime parser
// (backend/runtime/screening_library.py). Empty-file cases normalize to zero
// compounds with no parse errors — the 'no compound records' rejection belongs to
// the file-level wrappers on both sides (buildVirtualScreeningYaml here,
// parse_screening_compounds_file there).
const CASES: Array<{ input: string; error: string | null; compounds: Array<{ id: string; name: string; smiles: string }> }> = [
  {
    "input": ">aspirin\nCC(=O)OC1=CC=CC=C1C(=O)O\n>caffeine\nCn1c(=O)c2c(ncn2C)n(C)c1=O\n",
    "error": null,
    "compounds": [
      {
        "id": "aspirin",
        "name": "aspirin",
        "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O"
      },
      {
        "id": "caffeine",
        "name": "caffeine",
        "smiles": "Cn1c(=O)c2c(ncn2C)n(C)c1=O"
      }
    ]
  },
  {
    "input": "CCO ethanol\nc1ccccc1 benzene\n",
    "error": null,
    "compounds": [
      {
        "id": "ethanol",
        "name": "ethanol",
        "smiles": "CCO"
      },
      {
        "id": "benzene",
        "name": "benzene",
        "smiles": "c1ccccc1"
      }
    ]
  },
  {
    "input": "CCO\nc1ccccc1\n",
    "error": null,
    "compounds": [
      {
        "id": "compound-1",
        "name": "Compound 1",
        "smiles": "CCO"
      },
      {
        "id": "compound-2",
        "name": "Compound 2",
        "smiles": "c1ccccc1"
      }
    ]
  },
  {
    "input": "smiles,name\nCCO,ethanol\nc1ccccc1,benzene\n",
    "error": null,
    "compounds": [
      {
        "id": "ethanol",
        "name": "ethanol",
        "smiles": "CCO"
      },
      {
        "id": "benzene",
        "name": "benzene",
        "smiles": "c1ccccc1"
      }
    ]
  },
  {
    "input": "canonical_smiles,compound_name\nCCO,ethanol\n",
    "error": null,
    "compounds": [
      {
        "id": "ethanol",
        "name": "ethanol",
        "smiles": "CCO"
      }
    ]
  },
  {
    "input": "CCO\tethanol\nc1ccccc1\tbenzene\n",
    "error": null,
    "compounds": [
      {
        "id": "ethanol",
        "name": "ethanol",
        "smiles": "CCO"
      },
      {
        "id": "benzene",
        "name": "benzene",
        "smiles": "c1ccccc1"
      }
    ]
  },
  {
    "input": "smiles,name\n\"CCO\",\"ethyl alcohol\"\n",
    "error": null,
    "compounds": [
      {
        "id": "ethyl-alcohol",
        "name": "ethyl alcohol",
        "smiles": "CCO"
      }
    ]
  },
  {
    "input": ">dup\nCCO\n>dup\nCCS\n",
    "error": null,
    "compounds": [
      {
        "id": "dup",
        "name": "dup",
        "smiles": "CCO"
      },
      {
        "id": "dup-2",
        "name": "dup",
        "smiles": "CCS"
      }
    ]
  },
  {
    "input": ">aspirin\nCCO\n",
    "error": null,
    "compounds": [
      {
        "id": "aspirin",
        "name": "aspirin",
        "smiles": "CCO"
      }
    ]
  },
  {
    "input": ">aspirin\r\nCCO\r\n",
    "error": null,
    "compounds": [
      {
        "id": "aspirin",
        "name": "aspirin",
        "smiles": "CCO"
      }
    ]
  },
  {
    "input": ">mixed\nCCO extra tokens\n",
    "error": null,
    "compounds": [
      {
        "id": "mixed",
        "name": "mixed",
        "smiles": "CCO"
      }
    ]
  },
  {
    "input": "# comment only\n",
    "error": null,
    "compounds": []
  },
  {
    "input": "",
    "error": null,
    "compounds": []
  },
  {
    "input": ">\nCCO\n",
    "error": "Line 2: expected a record header beginning with \">\".",
    "compounds": []
  },
  {
    "input": ">orphan\n>filled\nCCO\n",
    "error": "Compound orphan: SMILES is missing.",
    "compounds": []
  },
  {
    "input": "smiles,name\n,ethanol\n",
    "error": "Line 2: SMILES is missing.",
    "compounds": []
  },
  {
    "input": "smiles,name\n\"CCO,ethanol\n",
    "error": "Line 2: unterminated quoted field.",
    "compounds": []
  },
  {
    "input": "smiles,name\n,ethanol\nCCO,late\n",
    "error": "Line 2: SMILES is missing.",
    "compounds": []
  },
  {
    "input": "CCO\tname1\n\tCCN\tname2\n",
    "error": "Line 2: SMILES is missing.",
    "compounds": []
  },
  {
    "input": "CCO\tname1\t\n",
    "error": null,
    "compounds": [
      {
        "id": "name1",
        "name": "name1",
        "smiles": "CCO"
      }
    ]
  },
  {
    "input": ">aًb\nCCO\n",
    "error": null,
    "compounds": [
      {
        "id": "a-b",
        "name": "aًb",
        "smiles": "CCO"
      }
    ]
  }
];

describe('TS parser matches the runtime parser on the full vector battery', () => {
  it('agrees on every vector', () => {
    for (const testCase of CASES) {
      const parsed = parseVirtualScreeningInput(testCase.input);
      if (testCase.error === null) {
        expect(parsed.errors, `input: ${JSON.stringify(testCase.input)}`).toEqual([]);
        expect(
          parsed.compounds.map((compound) => ({ id: compound.id, name: compound.name, smiles: compound.smiles })),
          `input: ${JSON.stringify(testCase.input)}`
        ).toEqual(testCase.compounds);
      } else {
        expect(parsed.errors.join(' '), `input: ${JSON.stringify(testCase.input)}`).toBe(testCase.error);
      }
    }
  });
});
